// <auto-generated />
using KolaNaukowe.web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KolaNaukowe.web.Migrations
{
    [DbContext(typeof(KolaNaukoweDbContext))]
    [Migration("20180402165537_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KolaNaukowe.web.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("StudentResearchGroupId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentResearchGroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("KolaNaukowe.web.Models.StudentResearchGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("StudentResearchGroups");
                });

            modelBuilder.Entity("KolaNaukowe.web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KolaNaukowe.web.Models.Student", b =>
                {
                    b.HasOne("KolaNaukowe.web.Models.StudentResearchGroup", "StudentResearchGroup")
                        .WithMany("Students")
                        .HasForeignKey("StudentResearchGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
